### ISSUE TITLE
Bug: Windows instances error with unsupported type

### ISSUE THREAD

**Issue by dan-hoeger** [aws-samples/eks-cluster-upgrade#100]
### Expected Behaviour

I would expect the windows nodes to be updgraded

### Current Behaviour

we get the following messages in the log

i-00936987c5fa16273
Node type: windows server 2019 datacenter is unsupported  - Image ID: ami-04ff2af787d4f4ed3
i-04cef8a13573d6b29
Node type: windows server 2019 datacenter is unsupported  - Image ID: ami-04ff2af787d4f4ed3

### Code snippet

```python3
na
```

### Possible Solution

I think line 29 in eksupgrade/src/get_image_type.py needs to be changed from:
    elif node_type == "windows":
to
    elif "windows" in node_type.lower():

this is what is used in eksupgrade/src/preflight_module.py on line 841 so we should be consistent.

I've modified this locally and was able to test this and it works.

### Steps to Reproduce

upgrade a cluster with windows nodes.

### Amazon EKS upgrade version

latest

### Python runtime version

3.10

### Packaging format used

Git clone

**Comment by quixoticmonk** [comment]
Acknowledging this. We should have updated logic for upgrades and pre-flight checks on the way. I will make a note to have this checked while we make the switch to the updated logic.
