### ISSUE TITLE
Bug: Node upgrade of Amazon Linux from 1.21 to 1.22

### ISSUE THREAD

**Issue by VijayganeshSubramaniam** [aws-samples/eks-cluster-upgrade#106]
### Expected Behaviour

Upgrading from 1.21 to 1.22 , node groups are creating but not attached the cluster.
Expectation the eksctl nodegroup cmd file required have overrideBootstrapCommand with below detail then only it would attached to the cluster.

As per the announcement https://eksctl.io/announcements/nodegroup-override-announcement/

### Current Behaviour

May be overrideBootstrapCommand is missing as part of  eksctl nodegroup cmd file so it is not attaching to the cluster.

### Code snippet

```python3
overrideBootstrapCommand: '#!/bin/bash

    source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

    /etc/eks/bootstrap.sh CLUSTER_NAME --kubelet-extra-args "--node-labels=${NODE_LABELS} "'
```

### Steps to Reproduce

upgrade eks-cluster-upgrade of cluster 1.21 of amazon linux 2 instances

### Amazon EKS upgrade version

latest

### Python runtime version

3.10

### Packaging format used

Git clone

### Debugging logs

```python3
NA
```

**Comment by quixoticmonk** [comment]
Thank you for opening the issue on this @VijayganeshSubramaniam .  Reviewing this.
