### ISSUE TITLE
Bug: Cluster upgrade from 1.24 to 1.25 Createnodegroup nodes are in not ready status

### ISSUE THREAD

**Issue by VijayganeshSubramaniam** [aws-samples/eks-cluster-upgrade#108]
### Expected Behaviour

EKS kubernetes cluster upgrade from 1.24 to 1.25 (amazon-eks-node-1.25) are created but cluster status shows as "Not Ready"

In 1.22, followed as mentioned in announcement https://eksctl.io/announcements/nodegroup-override-announcement/

The announcement supported for 1.22 -> 1.23 -> 1.24  

Similary any additional configuration to be done for 1.25

### Current Behaviour

1.24 to 1.25 Amazon Linux 2 in Not Ready status after 30 minutes of node creation.

### Code snippet

```python3
overrideBootstrapCommand: '#!/bin/bash

    source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh

    /etc/eks/bootstrap.sh CLUSTER_NAME --kubelet-extra-args "--node-labels=${NODE_LABELS} "'
```

### Steps to Reproduce

EKS cluster upgrade from 1.24 to 1.25 using eks-cluster-upgrade script

### Amazon EKS upgrade version

latest

### Python runtime version

3.10

### Packaging format used

Git clone

**Comment by dan-hoeger** [comment]
we are seeing the same issue.
we found that it is an issue with Coredns and Kubeproxy not getting updated

Coredns :   https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html 
Kubeproxy : https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html
