### ISSUE TITLE
Feature: Remove usage of `eksctl`

### ISSUE THREAD

**Issue by bryantbiggs** [aws-samples/eks-cluster-upgrade#32]
### Summary

`eksctl` already provides support for upgrading the control plane of a cluster created by its CLI https://eksctl.io/usage/cluster-upgrade/

This is mainly done just to keep the generated CloudFormation in-sync with any changes. It currently does not support upgrading any components of the data plane; these are handled in the same way that upgrades are handled here. Therefore, the data plane and addon upgrade logic and be used on clusters created by `eksctl` and a separate, unique process does not need to exists

### Why is this needed?

If users are using `eksctl` today, they should continue using it to perform upgrades of the control plane as per `eksctl`. Since `eksctl` does not support upgrading any components of the data plane, we can still support that process with `eksupgrade`

### Which area does this relate to?

Automation

### Solution

- We can keep [this](https://github.com/aws-samples/amazon-eks-one-click-cluster-upgrade/blob/cd88b2f10ec0be05d18c44026695767324dc4fd8/eksupgrade/src/eksctlfinal.py#L79) wrapped call to `eksctl` or we can replace it and instruct users to upgrade the control plane first. 

- Functionality will need to be added to support performing data plane only upgrades. This process will inspect the control plane version and update the data plane components to match (update nodegroups, Fargate profiles, addon default versions, etc.). This is useful both for the `eksctl` scenario as well as for the guidance provided to users to ensure the data plane components are aligned with the control plane prior to upgrading. Therefore, users can also use this functionality to align their data plane with the control plane prior to performing an upgrade

**Comment by bryantbiggs** [comment]
I guess this is more of a feature rather than maintenance (in hindsight)

**Comment by mbeacom** [comment]
The `eksctl` functionality is totally inaccessible to the enduser right now:  https://github.com/aws-samples/eks-cluster-upgrade/blob/85a60934c2087b95b935822d6c33caea022f49f5/eksupgrade/starter.py#L160-L161

We may as well remove it and if desired, re-add something in the new interface.
