### ISSUE TITLE
Maintenance: Consolidate cluster auth functionality

### ISSUE THREAD

**Issue by bryantbiggs** [aws-samples/eks-cluster-upgrade#33]
### Summary

Currently there are multiple cluster authentication means throughout the codebase:
1. https://github.com/aws-samples/amazon-eks-one-click-cluster-upgrade/blob/cd88b2f10ec0be05d18c44026695767324dc4fd8/eksupgrade/src/k8s_client.py#L59-L96
2. https://github.com/aws-samples/amazon-eks-one-click-cluster-upgrade/blob/cd88b2f10ec0be05d18c44026695767324dc4fd8/eksupgrade/src/eksctlfinal.py#L26-L66

This logic should be consolidated and mirror/use what is defined by the awscli https://github.com/aws/aws-cli/blob/develop/awscli/customizations/eks/update_kubeconfig.py

### Why is this needed?

1. Ensure logic is not repeated
2. Ensure that users are authenticated to the cluster correctly - this also removes the need for users to run `aws eks update-kubeconfig --name <name> ...` that is defined in the README.md getting started

### Which area does this relate to?

Other

### Solution

Logic is defined only once and aligns with the awscli functionality (it does not need to write a kubeconfig file, but the authn/authz logic should be matched)

**Comment by mbeacom** [comment]
This is WIP
