### ISSUE TITLE
Feature request: Support Kubernetes V1.25

### ISSUE THREAD

**Issue by quixoticmonk** [aws-samples/eks-cluster-upgrade#64]
### Use case

Currently, the maximum allowed version to upgrade to is `1.24`. EKS announced inclusion of [1.25 ](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html)version.

- Defined on `def get_cluster_version` in pre-flight checks and the version_dicts.

Validate if this is merely a version number update or additional changes need to be incorporated to support this version from the api and resource side. Notably PodSecurityPolicy is removed in favor of PSA( Pod Security Admission).

**Call outs from the documentation** : https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.25

### Solution/User Experience

Allows user to select `1.25` as a possible upgrade target.

**Comment by bryantbiggs** [comment]
I believe based on the recent changes made to the project, we no longer have any constraints and it should "just work" for 1.25 and any future versions (currently) - correct @mbeacom ?
