### ISSUE TITLE
Bug: Owner ID does not look correct for Windows AMI images

### ISSUE THREAD

**Issue by dan-hoeger** [aws-samples/eks-cluster-upgrade#92]
### Expected Behaviour

we are getting a message saying we have custom AMI's when we are using the latest Amazon windows AMI's for the EKS version specified.

our instances are using the following AMI
ami-087cc060ba1de1b6d https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-087cc060ba1de1b6d
Windows_Server-2019-English-Full-EKS_Optimized-1.21-2023.02.14
the owner for this AMI is 957547624766 but in the Preflight code it's looking for an owner of 801119661308

I don't find any EKS_Optimized windows images under that owner.

### Current Behaviour

getting the following message in the pre-flight

i-01c9ece320961ce5c cannot be upgraded as it uses a custom AMI!
i-06af7621a4c1c99d2 cannot be upgraded as it uses a custom AMI!

### Code snippet

```python
try to upgrade a cluster with windows nodes.
```

### Possible Solution

change the owner ID to 957547624766 in iscustomami method for the windows instances.

### Steps to Reproduce

try to upgrade a cluster with windows nodes.

### Amazon EKS upgrade version

1.22

### Python runtime version

3.9

### Packaging format used

Git clone

**Comment by quixoticmonk** [comment]
Thank you for bringing this up. Taking a look at the current amis for windows show the account id as `957547624766`. @mbeacom  Are we changing the underlying method here or do you want me to change the filters in a PR ?

**Comment by mbeacom** [comment]
@dan-hoeger Thanks for reporting this!

@quixoticmonk We can patch the existing implementation to resolve Dan's issue, but we are replacing this workflow totally in an upcoming release.

**Comment by mbeacom** [comment]
The fix (#93) for this issue will be released in `0.8.1` thanks to @quixoticmonk.

@dan-hoeger Thank you again for reporting this!

**Comment by mbeacom** [comment]
@dan-hoeger This bug fix is now released and available in `0.8.1` from PyPi!
